# -*- coding: utf-8 -*-
"""프로그래머스 day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13V44YjwyivWp4_m7uMJwMIeM6gwcumUv
"""

#day2_두 수의 나눗셈
def solution(num1, num2):
    answer = (num1 / num2) * 1000
    return int(answer)

#day2_숫자 비교하기
def solution(num1, num2):
    if num1 == num2:
        return 1
    else:
        return -1

#day2_분수의 덧셈
import math
def solution(denum1, num1, denum2, num2):
    bunja = (denum1 * num2) + (denum2 * num1)
    bunmo = num1 * num2
    d = math.gcd(bunja, bunmo)
    answer = [bunja/d, bunmo/d]
    return answer

#day2_배열 두 배 만들기
def solution(numbers):
    answer = []
    for i in numbers:
        answer.append(2 * i)
    return answer