# -*- coding: utf-8 -*-
"""프로그래머스_day4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l4x7DBpx61R-vPvW1aTXwJ50-haZrA5x
"""

#day4_피자 나눠 먹기(1)
def solution(n):
    if n <= 7:
        return 1
    elif n%7 == 0:
        return n//7
    elif n % 7 != 0:
        return n // 7 + 1

#day4_피자 나눠 먹기(2)
def solution(n):
    for i in range(max(n, 6), (n*6)+1):
        if i % n == 0 and i % 6 == 0:
            return i // 6

#day4_피자 나눠 먹기(3)
def solution(slice, n):
    if n % slice == 0:
        return n // slice
    else:
        return n // slice + 1

#day4_배열의 평균값
def solution(numbers):
    count = sum(numbers)
    num = count / len(numbers)
    if num - int(num) == 0 or num - int(num) == 0.5:
        return num