# -*- coding: utf-8 -*-
"""프로그래머스 day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GxY85W9h91Lq9h9zaB3p2NVzq0VCmF86

# 프로그래머스
"""

#Day1 두수의 합
def solution(num1, num2):
    answer = num1 + num2
    return answer

solution(2, 3)
solution(100, 2)

#Day1 두수의 차
def solution(num1, num2):
    answer = num1 - num2
    return answer

#Day1 두수의 곱
def solution(num1, num2):
    answer = num1*num2
    return answer

#Day1 몫구하기
def solution(num1, num2):
    answer = num1 // num2
    return answer