# -*- coding: utf-8 -*-
"""프로그래머스_day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zo7mc1FRxg8VJAJWDOvOmW9IlZKJL8rI
"""

#day3_나머지 구하기
def solution(num1, num2):
    answer = num1 % num2
    return answer

#day3_중앙값 구하기
import numpy as np
def solution(array):
    answer = np.median(array)
    return answer

#day3_최빈값 구하기
def solution(array):
    while len(array) != 0:
        for i, a in enumerate(set(array)):
            array.remove(a)
        if i == 0: return a
    return -1

#day3_짝수는 싫어요
def solution(n):
    answer = []
    for i in range(1, n+1):
        if i %2 == 1:
            answer.append(i)
    return answer